#ifndef JOYSTICK_MAP_PS3
#define JOYSTICK_MAP_PS3

/*
 * Controll input mapping of PS3 controller with sixaxis driver. 
 */


enum joystick_ps3_button 
{
	JOYSTICK_PS3_BUTTON_CROSS = 0,
	JOYSTICK_PS3_BUTTON_CIRCLE = 1,
	JOYSTICK_PS3_BUTTON_TRAINGLE = 2,
	JOYSTICK_PS3_BUTTON_SQUARE = 3,
	JOYSTICK_PS3_BUTTON_LEFT_TOP = 4,
	JOYSTICK_PS3_BUTTON_RIGHT_TOP = 5,
	JOYSTICK_PS3_BUTTON_LEFT_BOTTON = 6,
	JOYSTICK_PS3_BUTTON_RIGHT_BOTTOM = 7,
	JOYSTICK_PS3_BUTTON_SELECT = 8,
	JOYSTICK_PS3_BUTTON_START = 9,
	JOYSTICK_PS3_BUTTON_PSN = 10,
	JOYSTICK_PS3_BUTTON_JOYSTICK_LEFT = 11,
	JOYSTICK_PS3_BUTTON_JOYSTICK_RIGHT = 12,
	JOYSTICK_PS3_BUTTON_UP = 13,
	JOYSTICK_PS3_BUTTON_DOWN = 14,
	JOYSTICK_PS3_BUTTON_LEFT  = 15,
	JOYSTICK_PS3_BUTTON_RIGHT = 16,
	JOYSTICK_PS3_BUTTON_LENGTH = 17,
};

enum joystick_ps3_axis
{
	JOYSTICK_PS3_AXIS_LEFT_X = 0,
	JOYSTICK_PS3_AXIS_LEFT_Y = 1,
	JOYSTICK_PS3_AXIS_LEFT_BOTTON = 2,
	JOYSTICK_PS3_AXIS_RIGHT_X = 4,
	JOYSTICK_PS3_AXIS_RIGHT_Y = 3,
	JOYSTICK_PS3_AXIS_RIGHT_BOTTOM = 5,
	JOYSTICK_PS3_AXIS_LENGTH = 6,
};

struct joystick_ps3
{
	enum joystick_ps3_button button[JOYSTICK_PS3_BUTTON_LENGTH];
	enum joystick_ps3_axis 	axis[JOYSTICK_PS3_AXIS_LENGTH];
};


#endif 



